
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const User = require('../models/User');
const { generateBaseSlug } = require('../utils/slugGenerator');

// CONFIG
const DRY_RUN = false; // Execute immediately

// RULES
const GENERIC_NAMES = new Set(['founder', 'user', 'admin', 'unknown', 'anonymous', 'test', 'tester', 'demo', 'not specified', 'not publicly listed', 'no name']);
const PUBLIC_EMAIL_PROVIDERS = new Set(['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'aol.com', 'icloud.com', 'protonmail.com', 'mail.com']);
const FILLER_WORDS = ['official', 'profile', 'real', 'hq', 'org', 'net', 'site', 'web', 'online', 'now', 'connect', 'hub', 'box', 'space', 'zone', 'link', 'bio', 'page', 'home'];
const MAX_LENGTH = 50;

// HELPERS
const cleanName = (name) => {
    if (!name) return '';
    let cleaned = name.replace(/[^a-zA-Z\s]/g, '');
    cleaned = cleaned.replace(/\s+/g, ' ').trim();
    return cleaned;
};

const capitalize = (str) => str.replace(/\b\w/g, c => c.toUpperCase());

const deriveNameFromEmail = (email) => {
    if (!email) return 'Founder';
    const [local, domain] = email.split('@');
    if (!domain) return local;
    if (PUBLIC_EMAIL_PROVIDERS.has(domain.toLowerCase())) {
        const cleanLocal = local.replace(/[0-9]/g, '');
        return capitalize(cleanLocal.replace(/[._-]/g, ' ')).trim() || 'Founder';
    } else {
        const company = domain.split('.')[0];
        return `${capitalize(company)} Team`;
    }
};

const getEffectiveName = (founder) => {
    let name = cleanName(founder.name || '');
    const normalized = name.toLowerCase();
    if (!name || GENERIC_NAMES.has(normalized)) {
        if (founder.company_name && founder.company_name.length > 2) return cleanName(founder.company_name);
        if (founder.email) return deriveNameFromEmail(founder.email);
        return 'Entrepreneur';
    }
    return name;
};

const getLocationSuffix = (location) => {
    if (!location) return null;
    const loc = location.toLowerCase();
    if (loc.includes('india') || loc.includes('delhi') || loc.includes('bangalore')) return 'india';
    if (loc.includes('usa') || loc.includes('sf') || loc.includes('ny')) return 'usa';
    if (loc.includes('uk') || loc.includes('london')) return 'uk';
    return null;
};

const isCollision = (slug, existingSlugs) => existingSlugs.has(slug);

const fixDB = async (dbName, uri) => {
    if (!uri) {
        console.log(`[${dbName}] No URI. Skipping.`);
        return;
    }
    console.log(`\n------------------------------------------------`);
    console.log(`[${dbName}] Connecting to: ${uri.replace(/\/\/.*@/, '//***@')}`);

    try {
        await mongoose.connect(uri);
        console.log(`[${dbName}] Connected.`);

        const users = await User.find({});
        console.log(`[${dbName}] Found ${users.length} users.`);

        users.sort((a, b) => a._id.toString().localeCompare(b._id.toString()));

        // Pre-fill existing slugs
        const existingSlugs = new Set();
        users.forEach(u => { if (u.slug) existingSlugs.add(u.slug); });

        const updates = [];

        for (const user of users) {
            let isModified = false;
            let nameChanged = false;

            // 1. Fix Name
            const oldName = user.name;
            const betterName = getEffectiveName(user);

            if (oldName !== betterName) {
                user.name = betterName;
                nameChanged = true;
                isModified = true;
            }

            // 2. Fix Slug
            // If slug is missing OR contains numbers OR name changed OR explicitly bad
            // We just strictly regenerate base slug from current name
            let baseSlug = generateBaseSlug(user.name);
            if (baseSlug.length < 2) baseSlug = 'entrepreneur';

            let finalSlug = baseSlug;

            // Check if current slug is already perfect?
            // If existing slug is valid (no numbers) and matches base, keep it?
            // But valid slug might have numbers if generated by old logic 'not-specified-123'.
            // We want to kill numbers.
            // If current slug has numbers, regenerate.
            const currentSlugHasNumbers = user.slug && /[0-9]/.test(user.slug);
            const currentSlugBad = user.slug && (user.slug.includes('not-specified') || user.slug.includes('founder'));

            if (user.slug !== finalSlug || currentSlugHasNumbers || currentSlugBad || isModified) {
                // Regenerate logic with collision handling

                // Remove current slug from set temporarily to allow self-match? 
                // No, we are generating a NEW target.

                if (isCollision(finalSlug, existingSlugs)) {
                    // Collision resolution
                    let resolved = false;
                    const locSuffix = getLocationSuffix(user.location);

                    // Loc
                    if (locSuffix) {
                        const p = `${baseSlug}-${locSuffix}`;
                        if (!isCollision(p, existingSlugs)) { finalSlug = p; resolved = true; }
                    }

                    // Fillers
                    if (!resolved) {
                        for (const f of FILLER_WORDS) {
                            const p = `${baseSlug}-${f}`;
                            if (!isCollision(p, existingSlugs)) { finalSlug = p; resolved = true; break; }
                        }
                    }

                    // Double Fillers
                    if (!resolved) {
                        for (const f1 of FILLER_WORDS) {
                            for (const f2 of FILLER_WORDS) {
                                if (f1 === f2) continue;
                                const p = `${baseSlug}-${f1}-${f2}`;
                                if (!isCollision(p, existingSlugs)) { finalSlug = p; resolved = true; break; }
                            }
                            if (resolved) break;
                        }
                    }

                    // Fallback
                    if (!resolved) {
                        finalSlug = `the-${baseSlug}-official`;
                    }
                }

                // Commit to set
                existingSlugs.add(finalSlug);

                // If changed, mark update
                if (user.slug !== finalSlug || isModified) {
                    updates.push({
                        updateOne: {
                            filter: { _id: user._id },
                            update: { $set: { name: user.name, slug: finalSlug, role: 'FOUNDER' } }
                        }
                    });
                    console.log(`[${dbName}] UPDATE: ${oldName} -> ${user.name} | Slug: ${user.slug} -> ${finalSlug}`);
                }
            } else {
                // Slug is fine
            }
        }

        if (updates.length > 0) {
            console.log(`[${dbName}] Committing ${updates.length} updates...`);
            if (!DRY_RUN) {
                await User.bulkWrite(updates);
                console.log(`[${dbName}] Success.`);
            } else {
                console.log(`[${dbName}] DRY RUN - Skipped write.`);
            }
        } else {
            console.log(`[${dbName}] System Clean.`);
        }

    } catch (e) {
        console.error(`[${dbName}] Error:`, e);
    } finally {
        await mongoose.disconnect();
        console.log(`[${dbName}] Disconnected.`);
    }
};

const run = async () => {
    const MONGO_URI_DEV = (process.env.MONGO_URI_LOCAL || process.env.MONGO_URI || '').replace(/"/g, '');
    const MONGO_URI_PROD = (process.env.MONGO_URI_PROD || '').replace(/"/g, '');

    await fixDB('PROD', MONGO_URI_PROD);
    await fixDB('DEV', MONGO_URI_DEV);
}

run();
